// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RealStateSearchPortal.Infrastructure.Migrations
{
    [DbContext(typeof(RealStateSearchPortalDbContext))]
    partial class RealStateSearchPortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RealStateSearchPortal.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RealStateSearchPortal.Domain.Entities.Favorite", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("RealStateSearchPortal.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int>("CarSpots")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Melbourne",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 1,
                            Description = "Cozy Cottage 1 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/1/300/200",
                            ListingType = "Rent",
                            Price = 1244744m,
                            Title = "Cozy Cottage 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Perth",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 0,
                            Description = "Beachfront Condo 2 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/2/300/200",
                            ListingType = "Sale",
                            Price = 256453m,
                            Title = "Beachfront Condo 2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Melbourne",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 2,
                            Description = "Cozy Cottage 3 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/3/300/200",
                            ListingType = "Sale",
                            Price = 425605m,
                            Title = "Cozy Cottage 3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Brisbane",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 2,
                            Description = "Beachfront Condo 4 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/4/300/200",
                            ListingType = "Rent",
                            Price = 1484986m,
                            Title = "Beachfront Condo 4"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Perth",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 0,
                            Description = "Beachfront Condo 5 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/5/300/200",
                            ListingType = "Sale",
                            Price = 745013m,
                            Title = "Beachfront Condo 5"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Adelaide",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "City Apartment 6 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/6/300/200",
                            ListingType = "Rent",
                            Price = 871551m,
                            Title = "City Apartment 6"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Melbourne",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "Modern House 7 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/7/300/200",
                            ListingType = "Rent",
                            Price = 682266m,
                            Title = "Modern House 7"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Sydney",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 1,
                            Description = "Beachfront Condo 8 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/8/300/200",
                            ListingType = "Sale",
                            Price = 1625172m,
                            Title = "Beachfront Condo 8"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 1,
                            Description = "Modern House 9 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/9/300/200",
                            ListingType = "Sale",
                            Price = 698115m,
                            Title = "Modern House 9"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 2,
                            Description = "Modern House 10 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/10/300/200",
                            ListingType = "Sale",
                            Price = 433978m,
                            Title = "Modern House 10"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Adelaide",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 0,
                            Description = "Beachfront Condo 11 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/11/300/200",
                            ListingType = "Sale",
                            Price = 1425009m,
                            Title = "Beachfront Condo 11"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Melbourne",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 0,
                            Description = "Cozy Cottage 12 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/12/300/200",
                            ListingType = "Sale",
                            Price = 864960m,
                            Title = "Cozy Cottage 12"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Brisbane",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 0,
                            Description = "Beachfront Condo 13 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/13/300/200",
                            ListingType = "Sale",
                            Price = 1086988m,
                            Title = "Beachfront Condo 13"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Sydney",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 0,
                            Description = "Cozy Cottage 14 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/14/300/200",
                            ListingType = "Sale",
                            Price = 1369290m,
                            Title = "Cozy Cottage 14"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Adelaide",
                            Bathrooms = 2,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "Beachfront Condo 15 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/15/300/200",
                            ListingType = "Rent",
                            Price = 1425699m,
                            Title = "Beachfront Condo 15"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Perth",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 1,
                            Description = "Cozy Cottage 16 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/16/300/200",
                            ListingType = "Sale",
                            Price = 1229153m,
                            Title = "Cozy Cottage 16"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Brisbane",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "Cozy Cottage 17 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/17/300/200",
                            ListingType = "Rent",
                            Price = 1558635m,
                            Title = "Cozy Cottage 17"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Sydney",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 1,
                            Description = "Cozy Cottage 18 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/18/300/200",
                            ListingType = "Rent",
                            Price = 1047575m,
                            Title = "Cozy Cottage 18"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Melbourne",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 0,
                            Description = "Luxury Villa 19 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/19/300/200",
                            ListingType = "Sale",
                            Price = 1473341m,
                            Title = "Luxury Villa 19"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 2,
                            Description = "City Apartment 20 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/20/300/200",
                            ListingType = "Sale",
                            Price = 1901216m,
                            Title = "City Apartment 20"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Perth",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 1,
                            Description = "City Apartment 21 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/21/300/200",
                            ListingType = "Rent",
                            Price = 627792m,
                            Title = "City Apartment 21"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Perth",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 0,
                            Description = "Beachfront Condo 22 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/22/300/200",
                            ListingType = "Sale",
                            Price = 1741496m,
                            Title = "Beachfront Condo 22"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Sydney",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 0,
                            Description = "Cozy Cottage 23 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/23/300/200",
                            ListingType = "Sale",
                            Price = 613572m,
                            Title = "Cozy Cottage 23"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Sydney",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "City Apartment 24 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/24/300/200",
                            ListingType = "Sale",
                            Price = 1253866m,
                            Title = "City Apartment 24"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Sydney",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 0,
                            Description = "Beachfront Condo 25 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/25/300/200",
                            ListingType = "Sale",
                            Price = 1820780m,
                            Title = "Beachfront Condo 25"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Adelaide",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 2,
                            Description = "Cozy Cottage 26 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/26/300/200",
                            ListingType = "Rent",
                            Price = 439527m,
                            Title = "Cozy Cottage 26"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Melbourne",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 2,
                            Description = "City Apartment 27 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/27/300/200",
                            ListingType = "Sale",
                            Price = 1775916m,
                            Title = "City Apartment 27"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Sydney",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 0,
                            Description = "Modern House 28 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/28/300/200",
                            ListingType = "Sale",
                            Price = 1392568m,
                            Title = "Modern House 28"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Adelaide",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 1,
                            Description = "City Apartment 29 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/29/300/200",
                            ListingType = "Sale",
                            Price = 1147502m,
                            Title = "City Apartment 29"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Perth",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 0,
                            Description = "Luxury Villa 30 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/30/300/200",
                            ListingType = "Rent",
                            Price = 1571343m,
                            Title = "Luxury Villa 30"
                        },
                        new
                        {
                            Id = 31,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 0,
                            Description = "Modern House 31 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/31/300/200",
                            ListingType = "Sale",
                            Price = 869290m,
                            Title = "Modern House 31"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Sydney",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 1,
                            Description = "Modern House 32 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/32/300/200",
                            ListingType = "Sale",
                            Price = 532837m,
                            Title = "Modern House 32"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Sydney",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "City Apartment 33 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/33/300/200",
                            ListingType = "Sale",
                            Price = 600890m,
                            Title = "City Apartment 33"
                        },
                        new
                        {
                            Id = 34,
                            Address = "Brisbane",
                            Bathrooms = 2,
                            Bedrooms = 5,
                            CarSpots = 2,
                            Description = "Cozy Cottage 34 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/34/300/200",
                            ListingType = "Rent",
                            Price = 1227063m,
                            Title = "Cozy Cottage 34"
                        },
                        new
                        {
                            Id = 35,
                            Address = "Brisbane",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 0,
                            Description = "Beachfront Condo 35 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/35/300/200",
                            ListingType = "Sale",
                            Price = 356581m,
                            Title = "Beachfront Condo 35"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Perth",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "Modern House 36 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/36/300/200",
                            ListingType = "Sale",
                            Price = 1337918m,
                            Title = "Modern House 36"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Perth",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 1,
                            Description = "Cozy Cottage 37 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/37/300/200",
                            ListingType = "Sale",
                            Price = 585629m,
                            Title = "Cozy Cottage 37"
                        },
                        new
                        {
                            Id = 38,
                            Address = "Sydney",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 2,
                            Description = "City Apartment 38 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/38/300/200",
                            ListingType = "Sale",
                            Price = 1536761m,
                            Title = "City Apartment 38"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 0,
                            Description = "City Apartment 39 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/39/300/200",
                            ListingType = "Rent",
                            Price = 1432299m,
                            Title = "City Apartment 39"
                        },
                        new
                        {
                            Id = 40,
                            Address = "Perth",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 0,
                            Description = "City Apartment 40 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/40/300/200",
                            ListingType = "Sale",
                            Price = 1585664m,
                            Title = "City Apartment 40"
                        },
                        new
                        {
                            Id = 41,
                            Address = "Adelaide",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 1,
                            Description = "Modern House 41 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/41/300/200",
                            ListingType = "Rent",
                            Price = 1801711m,
                            Title = "Modern House 41"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Sydney",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "Beachfront Condo 42 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/42/300/200",
                            ListingType = "Sale",
                            Price = 1005625m,
                            Title = "Beachfront Condo 42"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Sydney",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CarSpots = 0,
                            Description = "Modern House 43 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/43/300/200",
                            ListingType = "Sale",
                            Price = 1372494m,
                            Title = "Modern House 43"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Melbourne",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 2,
                            Description = "Cozy Cottage 44 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/44/300/200",
                            ListingType = "Rent",
                            Price = 937798m,
                            Title = "Cozy Cottage 44"
                        },
                        new
                        {
                            Id = 45,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 0,
                            Description = "Cozy Cottage 45 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/45/300/200",
                            ListingType = "Sale",
                            Price = 778124m,
                            Title = "Cozy Cottage 45"
                        },
                        new
                        {
                            Id = 46,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 0,
                            Description = "Modern House 46 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/46/300/200",
                            ListingType = "Sale",
                            Price = 1048215m,
                            Title = "Modern House 46"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Melbourne",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 2,
                            Description = "Beachfront Condo 47 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/47/300/200",
                            ListingType = "Sale",
                            Price = 940200m,
                            Title = "Beachfront Condo 47"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Adelaide",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 0,
                            Description = "Luxury Villa 48 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/48/300/200",
                            ListingType = "Rent",
                            Price = 1944116m,
                            Title = "Luxury Villa 48"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Perth",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 2,
                            Description = "City Apartment 49 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/49/300/200",
                            ListingType = "Sale",
                            Price = 895103m,
                            Title = "City Apartment 49"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Perth",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "Luxury Villa 50 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/50/300/200",
                            ListingType = "Sale",
                            Price = 251158m,
                            Title = "Luxury Villa 50"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Brisbane",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "Modern House 51 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/51/300/200",
                            ListingType = "Rent",
                            Price = 478251m,
                            Title = "Modern House 51"
                        },
                        new
                        {
                            Id = 52,
                            Address = "Sydney",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 0,
                            Description = "Beachfront Condo 52 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/52/300/200",
                            ListingType = "Sale",
                            Price = 266686m,
                            Title = "Beachfront Condo 52"
                        },
                        new
                        {
                            Id = 53,
                            Address = "Melbourne",
                            Bathrooms = 1,
                            Bedrooms = 4,
                            CarSpots = 1,
                            Description = "City Apartment 53 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/53/300/200",
                            ListingType = "Sale",
                            Price = 876348m,
                            Title = "City Apartment 53"
                        },
                        new
                        {
                            Id = 54,
                            Address = "Adelaide",
                            Bathrooms = 2,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "Beachfront Condo 54 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/54/300/200",
                            ListingType = "Rent",
                            Price = 1664271m,
                            Title = "Beachfront Condo 54"
                        },
                        new
                        {
                            Id = 55,
                            Address = "Brisbane",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 0,
                            Description = "Luxury Villa 55 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/55/300/200",
                            ListingType = "Rent",
                            Price = 1885585m,
                            Title = "Luxury Villa 55"
                        },
                        new
                        {
                            Id = 56,
                            Address = "Adelaide",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CarSpots = 0,
                            Description = "Cozy Cottage 56 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/56/300/200",
                            ListingType = "Rent",
                            Price = 1840776m,
                            Title = "Cozy Cottage 56"
                        },
                        new
                        {
                            Id = 57,
                            Address = "Perth",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 2,
                            Description = "Cozy Cottage 57 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/57/300/200",
                            ListingType = "Sale",
                            Price = 1800608m,
                            Title = "Cozy Cottage 57"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Perth",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CarSpots = 1,
                            Description = "City Apartment 58 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/58/300/200",
                            ListingType = "Sale",
                            Price = 752005m,
                            Title = "City Apartment 58"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Melbourne",
                            Bathrooms = 2,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "City Apartment 59 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/59/300/200",
                            ListingType = "Rent",
                            Price = 1928249m,
                            Title = "City Apartment 59"
                        },
                        new
                        {
                            Id = 60,
                            Address = "Melbourne",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 0,
                            Description = "Modern House 60 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/60/300/200",
                            ListingType = "Sale",
                            Price = 1558574m,
                            Title = "Modern House 60"
                        },
                        new
                        {
                            Id = 61,
                            Address = "Adelaide",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 2,
                            Description = "Modern House 61 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/61/300/200",
                            ListingType = "Sale",
                            Price = 897474m,
                            Title = "Modern House 61"
                        },
                        new
                        {
                            Id = 62,
                            Address = "Sydney",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 0,
                            Description = "Cozy Cottage 62 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/62/300/200",
                            ListingType = "Rent",
                            Price = 1196851m,
                            Title = "Cozy Cottage 62"
                        },
                        new
                        {
                            Id = 63,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 0,
                            Description = "City Apartment 63 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/63/300/200",
                            ListingType = "Sale",
                            Price = 655297m,
                            Title = "City Apartment 63"
                        },
                        new
                        {
                            Id = 64,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 1,
                            Description = "Cozy Cottage 64 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/64/300/200",
                            ListingType = "Sale",
                            Price = 850079m,
                            Title = "Cozy Cottage 64"
                        },
                        new
                        {
                            Id = 65,
                            Address = "Melbourne",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 2,
                            Description = "Beachfront Condo 65 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/65/300/200",
                            ListingType = "Sale",
                            Price = 544056m,
                            Title = "Beachfront Condo 65"
                        },
                        new
                        {
                            Id = 66,
                            Address = "Melbourne",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "Luxury Villa 66 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/66/300/200",
                            ListingType = "Sale",
                            Price = 1701614m,
                            Title = "Luxury Villa 66"
                        },
                        new
                        {
                            Id = 67,
                            Address = "Brisbane",
                            Bathrooms = 1,
                            Bedrooms = 4,
                            CarSpots = 1,
                            Description = "City Apartment 67 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/67/300/200",
                            ListingType = "Rent",
                            Price = 1694767m,
                            Title = "City Apartment 67"
                        },
                        new
                        {
                            Id = 68,
                            Address = "Sydney",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "Beachfront Condo 68 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/68/300/200",
                            ListingType = "Sale",
                            Price = 1882983m,
                            Title = "Beachfront Condo 68"
                        },
                        new
                        {
                            Id = 69,
                            Address = "Perth",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "Beachfront Condo 69 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/69/300/200",
                            ListingType = "Sale",
                            Price = 691525m,
                            Title = "Beachfront Condo 69"
                        },
                        new
                        {
                            Id = 70,
                            Address = "Perth",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 0,
                            Description = "Modern House 70 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/70/300/200",
                            ListingType = "Sale",
                            Price = 1224515m,
                            Title = "Modern House 70"
                        },
                        new
                        {
                            Id = 71,
                            Address = "Brisbane",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "City Apartment 71 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/71/300/200",
                            ListingType = "Rent",
                            Price = 522399m,
                            Title = "City Apartment 71"
                        },
                        new
                        {
                            Id = 72,
                            Address = "Sydney",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 2,
                            Description = "Cozy Cottage 72 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/72/300/200",
                            ListingType = "Sale",
                            Price = 1893982m,
                            Title = "Cozy Cottage 72"
                        },
                        new
                        {
                            Id = 73,
                            Address = "Sydney",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 0,
                            Description = "Cozy Cottage 73 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/73/300/200",
                            ListingType = "Rent",
                            Price = 258279m,
                            Title = "Cozy Cottage 73"
                        },
                        new
                        {
                            Id = 74,
                            Address = "Melbourne",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 2,
                            Description = "Luxury Villa 74 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/74/300/200",
                            ListingType = "Sale",
                            Price = 644800m,
                            Title = "Luxury Villa 74"
                        },
                        new
                        {
                            Id = 75,
                            Address = "Sydney",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 1,
                            Description = "Beachfront Condo 75 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/75/300/200",
                            ListingType = "Sale",
                            Price = 1770319m,
                            Title = "Beachfront Condo 75"
                        },
                        new
                        {
                            Id = 76,
                            Address = "Melbourne",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 2,
                            Description = "City Apartment 76 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/76/300/200",
                            ListingType = "Sale",
                            Price = 952304m,
                            Title = "City Apartment 76"
                        },
                        new
                        {
                            Id = 77,
                            Address = "Brisbane",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CarSpots = 2,
                            Description = "Cozy Cottage 77 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/77/300/200",
                            ListingType = "Rent",
                            Price = 480933m,
                            Title = "Cozy Cottage 77"
                        },
                        new
                        {
                            Id = 78,
                            Address = "Adelaide",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 0,
                            Description = "Beachfront Condo 78 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/78/300/200",
                            ListingType = "Sale",
                            Price = 1013933m,
                            Title = "Beachfront Condo 78"
                        },
                        new
                        {
                            Id = 79,
                            Address = "Adelaide",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 0,
                            Description = "City Apartment 79 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/79/300/200",
                            ListingType = "Sale",
                            Price = 1093305m,
                            Title = "City Apartment 79"
                        },
                        new
                        {
                            Id = 80,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "Luxury Villa 80 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/80/300/200",
                            ListingType = "Sale",
                            Price = 868950m,
                            Title = "Luxury Villa 80"
                        },
                        new
                        {
                            Id = 81,
                            Address = "Brisbane",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 1,
                            Description = "City Apartment 81 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/81/300/200",
                            ListingType = "Rent",
                            Price = 1132323m,
                            Title = "City Apartment 81"
                        },
                        new
                        {
                            Id = 82,
                            Address = "Sydney",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 1,
                            Description = "Cozy Cottage 82 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/82/300/200",
                            ListingType = "Rent",
                            Price = 786421m,
                            Title = "Cozy Cottage 82"
                        },
                        new
                        {
                            Id = 83,
                            Address = "Brisbane",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 1,
                            Description = "Cozy Cottage 83 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/83/300/200",
                            ListingType = "Rent",
                            Price = 240520m,
                            Title = "Cozy Cottage 83"
                        },
                        new
                        {
                            Id = 84,
                            Address = "Melbourne",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "Luxury Villa 84 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/84/300/200",
                            ListingType = "Sale",
                            Price = 1744728m,
                            Title = "Luxury Villa 84"
                        },
                        new
                        {
                            Id = 85,
                            Address = "Melbourne",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 1,
                            Description = "Beachfront Condo 85 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/85/300/200",
                            ListingType = "Sale",
                            Price = 695800m,
                            Title = "Beachfront Condo 85"
                        },
                        new
                        {
                            Id = 86,
                            Address = "Melbourne",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 2,
                            Description = "Modern House 86 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/86/300/200",
                            ListingType = "Sale",
                            Price = 1299972m,
                            Title = "Modern House 86"
                        },
                        new
                        {
                            Id = 87,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 2,
                            Description = "Luxury Villa 87 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/87/300/200",
                            ListingType = "Sale",
                            Price = 1493368m,
                            Title = "Luxury Villa 87"
                        },
                        new
                        {
                            Id = 88,
                            Address = "Brisbane",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 1,
                            Description = "Beachfront Condo 88 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/88/300/200",
                            ListingType = "Sale",
                            Price = 1353147m,
                            Title = "Beachfront Condo 88"
                        },
                        new
                        {
                            Id = 89,
                            Address = "Perth",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 0,
                            Description = "Luxury Villa 89 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/89/300/200",
                            ListingType = "Rent",
                            Price = 212088m,
                            Title = "Luxury Villa 89"
                        },
                        new
                        {
                            Id = 90,
                            Address = "Sydney",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 1,
                            Description = "Luxury Villa 90 located in Sydney",
                            ImageUrls = "https://picsum.photos/seed/90/300/200",
                            ListingType = "Rent",
                            Price = 1624867m,
                            Title = "Luxury Villa 90"
                        },
                        new
                        {
                            Id = 91,
                            Address = "Adelaide",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 0,
                            Description = "City Apartment 91 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/91/300/200",
                            ListingType = "Rent",
                            Price = 414325m,
                            Title = "City Apartment 91"
                        },
                        new
                        {
                            Id = 92,
                            Address = "Brisbane",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 2,
                            Description = "Luxury Villa 92 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/92/300/200",
                            ListingType = "Rent",
                            Price = 348122m,
                            Title = "Luxury Villa 92"
                        },
                        new
                        {
                            Id = 93,
                            Address = "Perth",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 0,
                            Description = "Beachfront Condo 93 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/93/300/200",
                            ListingType = "Rent",
                            Price = 1269319m,
                            Title = "Beachfront Condo 93"
                        },
                        new
                        {
                            Id = 94,
                            Address = "Perth",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 1,
                            Description = "Modern House 94 located in Perth",
                            ImageUrls = "https://picsum.photos/seed/94/300/200",
                            ListingType = "Rent",
                            Price = 294751m,
                            Title = "Modern House 94"
                        },
                        new
                        {
                            Id = 95,
                            Address = "Adelaide",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 2,
                            Description = "Beachfront Condo 95 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/95/300/200",
                            ListingType = "Sale",
                            Price = 812672m,
                            Title = "Beachfront Condo 95"
                        },
                        new
                        {
                            Id = 96,
                            Address = "Melbourne",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 0,
                            Description = "Luxury Villa 96 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/96/300/200",
                            ListingType = "Rent",
                            Price = 825992m,
                            Title = "Luxury Villa 96"
                        },
                        new
                        {
                            Id = 97,
                            Address = "Brisbane",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 2,
                            Description = "City Apartment 97 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/97/300/200",
                            ListingType = "Sale",
                            Price = 274284m,
                            Title = "City Apartment 97"
                        },
                        new
                        {
                            Id = 98,
                            Address = "Adelaide",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 1,
                            Description = "Luxury Villa 98 located in Adelaide",
                            ImageUrls = "https://picsum.photos/seed/98/300/200",
                            ListingType = "Sale",
                            Price = 612213m,
                            Title = "Luxury Villa 98"
                        },
                        new
                        {
                            Id = 99,
                            Address = "Brisbane",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 2,
                            Description = "Luxury Villa 99 located in Brisbane",
                            ImageUrls = "https://picsum.photos/seed/99/300/200",
                            ListingType = "Sale",
                            Price = 319977m,
                            Title = "Luxury Villa 99"
                        },
                        new
                        {
                            Id = 100,
                            Address = "Melbourne",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 1,
                            Description = "Beachfront Condo 100 located in Melbourne",
                            ImageUrls = "https://picsum.photos/seed/100/300/200",
                            ListingType = "Sale",
                            Price = 1284706m,
                            Title = "Beachfront Condo 100"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RealStateSearchPortal.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RealStateSearchPortal.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealStateSearchPortal.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RealStateSearchPortal.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealStateSearchPortal.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("RealStateSearchPortal.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealStateSearchPortal.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealStateSearchPortal.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
